import re

with open("index.js", "r", encoding="utf-8") as f:
    code = f.read()

print("[INFO] Original index.js length:", len(code))

# 0. Add LOCAL_AI_URL config after CORS / EXPRESS init or around line 785
if "LOCAL_AI_URL" not in code:
    code = code.replace(
        "const genAI = new GoogleGenerativeAI(",
        "const FormData = require('form-data');\nconst LOCAL_AI_URL = 'http://localhost:5000';\n// const genAI = new GoogleGenerativeAI("
    )
    print("[OK] Added LOCAL_AI_URL configuration.")

# 1. Replace /analyze
old_analyze = """      // LOAD GEMINI MODEL

      const model =
        genAI.getGenerativeModel({

          model: "gemini-2.5-flash-lite",

        });

      // PROCESS MEDIA
      if (!req.file) {
        return res.status(400).json({ error: 'No media file provided in the request.' });
      }
      let fileMimeType = req.file.mimetype;
      if (fileMimeType === 'application/octet-stream' || !fileMimeType) {
        const ext = (req.file.originalname || '').split('.').pop().toLowerCase();
        if (['jpg', 'jpeg'].includes(ext)) fileMimeType = 'image/jpeg';
        else if (ext === 'png') fileMimeType = 'image/png';
        else if (ext === 'webp') fileMimeType = 'image/webp';
        else if (ext === 'mp4') fileMimeType = 'video/mp4';
        else if (['mp3', 'wav', 'm4a', 'aac'].includes(ext)) fileMimeType = 'audio/mp3';
        else fileMimeType = 'image/jpeg';
      }
      let mediaPart;
      const scanLevel = deepScan ? "Perform a rigorous, multi-step deep scan analysis" : "Perform a standard analysis";
      let dynamicPrompt = `Analyze this uploaded media carefully. ${scanLevel}`;

      if (fileMimeType.startsWith('video/') || fileMimeType.startsWith('audio/')) {
        const fileManager = new GoogleAIFileManager(process.env.GEMINI_API_KEY);
        
        const uploadResponse = await fileManager.uploadFile(req.file.path, {
          mimeType: fileMimeType,
          displayName: req.file.originalname || "upload",
        });
        
        let fileState = await fileManager.getFile(uploadResponse.file.name);
        while (fileState.state === 'PROCESSING') {
          await new Promise((resolve) => setTimeout(resolve, 3000));
          fileState = await fileManager.getFile(uploadResponse.file.name);
        }
        
        if (fileState.state === 'FAILED') {
          throw new Error('Media processing failed.');
        }

        mediaPart = {
          fileData: {
            mimeType: uploadResponse.file.mimeType,
            fileUri: uploadResponse.file.uri
          }
        };

        if (fileMimeType.startsWith('audio/')) {
          dynamicPrompt = "Analyze this uploaded audio/voice recording carefully. Determine if it is a deepfake, an AI voice clone, or an authentic human voice. Look for robotic intonations, unnatural breathing patterns, or synthesis artifacts.";
        } else {
          dynamicPrompt = "Analyze this uploaded video carefully. Determine whether the video appears authentic or AI-generated. Look for temporal inconsistencies, morphing artifacts, unnatural physics, or deepfake face swapping.";
        }
      } else if (!fileMimeType.startsWith('image/')) {
        let extractedText = "";
        const filePath = req.file.path;
        const ext = (req.file.originalname || '').split('.').pop().toLowerCase();
        
        if (ext === 'pdf' || fileMimeType === 'application/pdf') {
          const dataBuffer = fs.readFileSync(filePath);
          const pdfData = await pdfParse(dataBuffer);
          extractedText = pdfData.text;
        } else if (ext === 'docx' || ext === 'doc' || fileMimeType === 'application/vnd.openxmlformats-officedocument.wordprocessingml.document') {
          try {
             const result = await mammoth.extractRawText({ path: filePath });
             extractedText = result.value;
          } catch(e) {
             extractedText = fs.readFileSync(filePath, 'utf8');
          }
        } else {
          extractedText = fs.readFileSync(filePath, 'utf8');
        }

        mediaPart = null;
        dynamicPrompt = `Analyze this document text carefully. Determine whether this text appears to be written by a human or generated by an AI (like ChatGPT, Claude, etc). Provide a professional analysis of perplexity, burstiness, AI-specific vocabulary and stylistic fingerprints. Here is the document content: \\n\\n"${extractedText}"`;
      } else {
        const imageBuffer = fs.readFileSync(req.file.path);
        mediaPart = {
          inlineData: {
            data: imageBuffer.toString("base64"),
            mimeType: fileMimeType,
          },
        };
        dynamicPrompt = "Analyze this uploaded image carefully. Determine whether the media appears authentic or AI-generated. Look for visual inconsistencies, AI-generated artifacts, and editing indicators.";
      }

      // AI PROMPT
      const deepScanInstruction = userSettings.deepScan ? "(DEEP SCAN MODE ENABLED: Analyze at a rigorous forensic level. Provide a highly detailed and technical explanation of any anomalies found.) " : "";
    const prompt = deepScanInstruction + `
${dynamicPrompt}

You MUST return your response as a valid JSON object without any markdown formatting or backticks. 
The JSON must have the following exact structure:
{
  "aiProbability": number (from 0 to 100, representing the probability the media is AI generated),
  "trustScore": number (from 0 to 100, representing how trustworthy/authentic the media is),
  "status": string (either "Authentic" or "AI Generated"),
  "explanation": string (short professional explanation of the analysis)
}
`;

      // SEND TO GEMINI
      let result;
      if (mediaPart) {
        result = await model.generateContent([prompt, mediaPart]);
      } else {
        result = await model.generateContent([prompt]);
      }

      // GET RESPONSE

      let rawText = result.response.text();
      rawText = rawText.replace(/```json/gi, "").replace(/```/g, "").trim();
      
      let aiResponse;
      try {
        aiResponse = JSON.parse(rawText);
      } catch (err) {
        console.error("JSON Parse Error:", rawText);
        aiResponse = {
          aiProbability: 50,
          trustScore: 50,
          status: "Inconclusive",
          explanation: rawText
        };
      }

      // AI SCORES"""

new_analyze = """      // LOAD LOCAL AI MODEL (Replaces Google Gemini)
      if (!req.file) {
        return res.status(400).json({ error: 'No media file provided in the request.' });
      }
      let fileMimeType = req.file.mimetype || '';
      const ext = (req.file.originalname || '').split('.').pop().toLowerCase();
      
      let aiResponse;
      try {
        if (fileMimeType.startsWith('image/') || fileMimeType.startsWith('video/') || fileMimeType.startsWith('audio/') || ['jpg', 'jpeg', 'png', 'webp', 'mp4', 'mp3', 'wav', 'm4a', 'aac'].includes(ext)) {
          const form = new FormData();
          form.append('media', fs.createReadStream(req.file.path), req.file.originalname || 'upload');
          const localRes = await axios.post(`${LOCAL_AI_URL}/analyze`, form, { headers: form.getHeaders() });
          aiResponse = localRes.data;
        } else {
          let extractedText = "";
          const filePath = req.file.path;
          if (ext === 'pdf' || fileMimeType === 'application/pdf') {
            const dataBuffer = fs.readFileSync(filePath);
            const pdfData = await pdfParse(dataBuffer);
            extractedText = pdfData.text;
          } else if (ext === 'docx' || ext === 'doc' || fileMimeType === 'application/vnd.openxmlformats-officedocument.wordprocessingml.document') {
            try {
               const result = await mammoth.extractRawText({ path: filePath });
               extractedText = result.value;
            } catch(e) {
               extractedText = fs.readFileSync(filePath, 'utf8');
            }
          } else {
            extractedText = fs.readFileSync(filePath, 'utf8');
          }
          const localRes = await axios.post(`${LOCAL_AI_URL}/analyze-document`, { text: extractedText });
          aiResponse = localRes.data;
        }
      } catch (err) {
        console.error("Local AI Error:", err.message);
        aiResponse = {
          aiProbability: 50,
          trustScore: 50,
          status: "Inconclusive",
          explanation: "Local AI analysis incomplete or server offline."
        };
      }

      // AI SCORES"""

if old_analyze in code:
    code = code.replace(old_analyze, new_analyze)
    print("[OK] Replaced /analyze with Local AI.")
else:
    print("[WARN] Could not find exact old_analyze block.")

# 2. Replace /analyze-text
old_text = """      const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash-lite" });

      const deepScanInstruction = userSettings.deepScan ? "(DEEP SCAN MODE ENABLED: Analyze at a rigorous forensic level. Provide a highly detailed and technical explanation of any anomalies found.) " : "";
    const prompt = deepScanInstruction + `
Analyze the following text carefully.
Determine whether this text appears to be written by a human or generated by an AI (like ChatGPT, Claude, etc).
Provide a professional analysis of:
- perplexity and burstiness
- AI-specific vocabulary and stylistic fingerprints
- logical flow and sentence structure

You MUST return your response as a valid JSON object without any markdown formatting or backticks. 
The JSON must have the following exact structure:
{
  "aiProbability": number (from 0 to 100, representing the probability the text is AI generated),
  "trustScore": number (from 0 to 100, representing how trustworthy/human-written the text is),
  "status": string (either "Authentic" or "AI Generated"),
  "explanation": string (short professional explanation of the analysis)
}

Text to analyze:
"${text}"
`;

      const result = await model.generateContent([prompt]);
      
      let rawText = result.response.text();
      rawText = rawText.replace(/```json/gi, "").replace(/```/g, "").trim();
      
      let aiResponse;
      try {
        aiResponse = JSON.parse(rawText);
      } catch (err) {
        console.error("JSON Parse Error:", rawText);
        aiResponse = {
          aiProbability: 50,
          trustScore: 50,
          status: "Inconclusive",
          explanation: rawText
        };
      }"""

new_text = """      let aiResponse;
      try {
        const localRes = await axios.post(`${LOCAL_AI_URL}/analyze-text`, { text });
        aiResponse = localRes.data;
      } catch (err) {
        console.error("Local AI Error:", err.message);
        aiResponse = {
          aiProbability: 50,
          trustScore: 50,
          status: "Inconclusive",
          explanation: "Local AI analysis incomplete or server offline."
        };
      }"""

if old_text in code:
    code = code.replace(old_text, new_text)
    print("[OK] Replaced /analyze-text with Local AI.")
else:
    print("[WARN] Could not find exact old_text block.")

# 3. Replace /analyze-batch
old_batch = """      const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash-lite" });
      const results = [];

      for (let file of req.files) {
        let fileMimeType = file.mimetype;
        if (fileMimeType === 'application/octet-stream' || !fileMimeType) {
          const ext = (file.originalname || '').split('.').pop().toLowerCase();
          if (['jpg', 'jpeg'].includes(ext)) fileMimeType = 'image/jpeg';
          else if (ext === 'png') fileMimeType = 'image/png';
          else if (ext === 'webp') fileMimeType = 'image/webp';
          else if (ext === 'mp4') fileMimeType = 'video/mp4';
          else if (['mp3', 'wav', 'm4a', 'aac'].includes(ext)) fileMimeType = 'audio/mp3';
          else fileMimeType = 'image/jpeg';
        }
        let mediaPart;
        let dynamicPrompt = "Analyze this uploaded media carefully.";

        if (fileMimeType.startsWith('video/') || fileMimeType.startsWith('audio/')) {
          const fileManager = new GoogleAIFileManager(process.env.GEMINI_API_KEY);
          const uploadResponse = await fileManager.uploadFile(file.path, {
            mimeType: fileMimeType,
            displayName: file.originalname || "upload",
          });
          
          let fileState = await fileManager.getFile(uploadResponse.file.name);
          while (fileState.state === 'PROCESSING') {
            await new Promise((resolve) => setTimeout(resolve, 3000));
            fileState = await fileManager.getFile(uploadResponse.file.name);
          }
          
          if (fileState.state === 'FAILED') continue;

          mediaPart = { fileData: { mimeType: uploadResponse.file.mimeType, fileUri: uploadResponse.file.uri } };
          if (fileMimeType.startsWith('audio/')) {
            dynamicPrompt = "Analyze this uploaded audio/voice recording carefully. Determine if it is a deepfake or authentic.";
          } else {
            dynamicPrompt = "Analyze this uploaded video carefully. Determine whether the video appears authentic or AI-generated.";
          }
        } else {
          const imageBuffer = fs.readFileSync(file.path);
          mediaPart = { inlineData: { data: imageBuffer.toString("base64"), mimeType: fileMimeType } };
          dynamicPrompt = "Analyze this uploaded image carefully. Determine whether the media appears authentic or AI-generated.";
        }

        const deepScanInstruction = userSettings.deepScan ? "(DEEP SCAN MODE ENABLED: Analyze at a rigorous forensic level. Provide a highly detailed and technical explanation of any anomalies found.) " : "";
    const prompt = deepScanInstruction + `
${dynamicPrompt}
You MUST return your response as a valid JSON object without any markdown formatting or backticks. 
{
  "aiProbability": number (from 0 to 100),
  "trustScore": number (from 0 to 100),
  "status": string (either "Authentic" or "AI Generated"),
  "explanation": string (short professional explanation)
}
`;
        try {
          const result = await model.generateContent([prompt, mediaPart]);
          let rawText = result.response.text();
          rawText = rawText.replace(/```json/gi, "").replace(/```/g, "").trim();
          let aiResponse = JSON.parse(rawText);"""

new_batch = """      const results = [];

      for (let file of req.files) {
        let fileMimeType = file.mimetype || 'image/jpeg';
        let aiResponse;
        try {
          const form = new FormData();
          form.append('media', fs.createReadStream(file.path), file.originalname || 'upload');
          const localRes = await axios.post(`${LOCAL_AI_URL}/analyze`, form, { headers: form.getHeaders() });
          aiResponse = localRes.data;"""

if old_batch in code:
    code = code.replace(old_batch, new_batch)
    print("[OK] Replaced /analyze-batch with Local AI.")
else:
    print("[WARN] Could not find exact old_batch block.")

# 4. Replace /analyze-social
old_social = """    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash-lite" });
    const scanLevel = deepScan ? "Perform a rigorous, multi-step analysis" : "Perform a standard analysis";

    const deepScanInstruction = userSettings.deepScan ? "(DEEP SCAN MODE ENABLED: Analyze at a rigorous forensic level. Provide a highly detailed and technical explanation of any anomalies found.) " : "";
    const prompt = deepScanInstruction + `
      You are an expert at detecting bot behavior and synthetic identities on social media.
      ${scanLevel} on the social media handle: ${handle}.
      Since you cannot browse live, simulate a likely analysis for this type of handle based on common bot patterns.
      
      Respond STRICTLY with a raw JSON object (no markdown, no backticks).
      {
        "aiProbability": <number between 0 and 100>,
        "trustScore": <number between 0 and 100>,
        "status": "<exactly 'Authentic' or 'AI Generated/Bot'>",
        "explanation": "<1-2 sentence explanation>"
      }
    `;

    const aiResult = await model.generateContent(prompt);
    let rawText = aiResult.response.text().replace(/```json/gi, "").replace(/```/g, "").trim();
    const aiData = JSON.parse(rawText);"""

new_social = """    const localRes = await axios.post(`${LOCAL_AI_URL}/analyze-social`, { handle });
    const aiData = localRes.data;"""

if old_social in code:
    code = code.replace(old_social, new_social)
    print("[OK] Replaced /analyze-social with Local AI.")
else:
    print("[WARN] Could not find exact old_social block.")

# 5. Replace /analyze-document
old_doc = """    const deepScan = req.body.deepScan === 'true';
    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash-lite" });
    const fileMimeType = req.file.mimetype;
    
    // Upload document to Gemini (Gemini supports pdf and text)
    const fileManager = new GoogleAIFileManager(process.env.GEMINI_API_KEY);
    const uploadResponse = await fileManager.uploadFile(req.file.path, {
      mimeType: fileMimeType,
      displayName: req.file.originalname,
    });
    
    let fileState = await fileManager.getFile(uploadResponse.file.name);
    while (fileState.state === 'PROCESSING') {
      await new Promise((resolve) => setTimeout(resolve, 3000));
      fileState = await fileManager.getFile(uploadResponse.file.name);
    }
    
    if (fileState.state === 'FAILED') {
      throw new Error('Document processing failed.');
    }

    const scanLevel = deepScan ? "Perform a rigorous, multi-step deep scan analysis" : "Perform a standard analysis";
    const deepScanInstruction = userSettings.deepScan ? "(DEEP SCAN MODE ENABLED: Analyze at a rigorous forensic level. Provide a highly detailed and technical explanation of any anomalies found.) " : "";
    const prompt = deepScanInstruction + `
      You are an expert at detecting AI-generated text in documents (PDF/Word/Txt).
      ${scanLevel} on the uploaded document.
      
      Respond STRICTLY with a raw JSON object (no markdown, no backticks).
      {
        "aiProbability": <number between 0 and 100>,
        "trustScore": <number between 0 and 100>,
        "status": "<exactly 'Authentic' or 'AI Generated'>",
        "explanation": "<1-2 sentence explanation>"
      }
    `;

    const aiResult = await model.generateContent([
      prompt,
      { fileData: { mimeType: uploadResponse.file.mimeType, fileUri: uploadResponse.file.uri } }
    ]);
    
    let rawText = aiResult.response.text().replace(/```json/gi, "").replace(/```/g, "").trim();
    const aiData = JSON.parse(rawText);"""

new_doc = """    let docText = "";
    try {
      if (req.file.originalname.endsWith('.pdf')) {
        const pdfData = await pdfParse(fs.readFileSync(req.file.path));
        docText = pdfData.text;
      } else if (req.file.originalname.endsWith('.docx') || req.file.originalname.endsWith('.doc')) {
        const resWord = await mammoth.extractRawText({ path: req.file.path });
        docText = resWord.value;
      } else {
        docText = fs.readFileSync(req.file.path, 'utf8');
      }
    } catch(e) {
      docText = "Document content scan";
    }

    const localRes = await axios.post(`${LOCAL_AI_URL}/analyze-document`, { text: docText });
    const aiData = localRes.data;"""

if old_doc in code:
    code = code.replace(old_doc, new_doc)
    print("[OK] Replaced /analyze-document with Local AI.")
else:
    print("[WARN] Could not find exact old_doc block.")

# 6. Replace /analyze-url
old_url = r"""    // 3. Send to Gemini
    const model = genAI.getGenerativeModel({
      model: "gemini-2.5-flash-lite",
    });

    const deepScanInstruction = userSettings.deepScan ? "(DEEP SCAN MODE ENABLED: Analyze at a rigorous forensic level. Provide a highly detailed and technical explanation of any anomalies found.) " : "";
    const prompt = deepScanInstruction + `
      You are an expert at detecting AI-generated content, fake news, and misinformation.
      Analyze the following text extracted from a webpage (${url}).
      
      Website Text:
      "${pageText}"

      Determine if the content is likely Authentic (human-written, factual reporting) or AI Generated (synthetic, bot-written, deepfake news, hallucinatory).
      
      Respond STRICTLY with a raw JSON object (no markdown, no backticks).
      {
        "aiProbability": <number between 0 and 100>,
        "trustScore": <number between 0 and 100>,
        "status": "<exactly 'Authentic' or 'AI Generated'>",
        "explanation": "<1-2 sentence explanation>"
      }
    `;

    const aiResult = await model.generateContent(prompt);
    const responseText = aiResult.response.text();
    let jsonMatch = responseText.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      throw new Error("Failed to parse JSON from AI response");
    }
    const aiData = JSON.parse(jsonMatch[0]);"""

new_url = """    const localRes = await axios.post(`${LOCAL_AI_URL}/analyze-url`, { url, pageText });
    const aiData = localRes.data;"""

if old_url in code:
    code = code.replace(old_url, new_url)
    print("[OK] Replaced /analyze-url with Local AI.")
else:
    print("[WARN] Could not find exact old_url block.")

# 7. Replace /analyze-live-audio
old_audio = """    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash-lite" });
    const deepScanInstruction = userSettings.deepScan ? "(DEEP SCAN MODE ENABLED: Analyze at a rigorous forensic level. Provide a highly detailed and technical explanation of any anomalies found.) " : "";
    const prompt = deepScanInstruction + `
You are a live audio analysis engine. A user just streamed 5 seconds of audio to you.
Generate a realistic JSON response indicating whether this hypothetical audio stream sounded like an AI voice clone or a real human.
Return ONLY a raw JSON object.
{
  "aiProbability": number (from 0 to 100),
  "trustScore": number (from 0 to 100),
  "status": string (either "Authentic" or "AI Generated"),
  "explanation": string (short professional explanation of the acoustic telltales found)
}
`;
    const result = await model.generateContent(prompt);
    let rawText = result.response.text().replace(/```json/gi, "").replace(/```/g, "").trim();
    const aiResponse = JSON.parse(rawText);"""

new_audio = """    const localRes = await axios.post(`${LOCAL_AI_URL}/analyze-live-audio`, {});
    const aiResponse = localRes.data;"""

if old_audio in code:
    code = code.replace(old_audio, new_audio)
    print("[OK] Replaced /analyze-live-audio with Local AI.")
else:
    print("[WARN] Could not find exact old_audio block.")

# 8. Replace /quiz
old_quiz = """    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash-lite" });
    const deepScanInstruction = userSettings.deepScan ? "(DEEP SCAN MODE ENABLED: Analyze at a rigorous forensic level. Provide a highly detailed and technical explanation of any anomalies found.) " : "";
    const prompt = deepScanInstruction + `
Generate 3 realistic quiz questions for spotting deepfakes/AI.
Return ONLY a raw JSON array of objects without markdown formatting.
Each object must have:
- imageUrl (string, generate a valid url exactly like "https://picsum.photos/seed/[random_word]/800/600" replacing [random_word] with a random 5-letter word)
- isAiGenerated (boolean)
- explanation (string, explaining why it is or isn't AI generated based on typical tells)
`;
    const result = await model.generateContent(prompt);
    let rawText = result.response.text().replace(/```json/gi, "").replace(/```/g, "").trim();
    const questions = JSON.parse(rawText);"""

new_quiz = """    const localRes = await axios.get(`${LOCAL_AI_URL}/quiz`);
    const questions = localRes.data;"""

if old_quiz in code:
    code = code.replace(old_quiz, new_quiz)
    print("[OK] Replaced /quiz with Local AI.")
else:
    print("[WARN] Could not find exact old_quiz block.")

# 9. Replace /news
old_news = """    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash-lite" });
    const deepScanInstruction = userSettings.deepScan ? "(DEEP SCAN MODE ENABLED: Analyze at a rigorous forensic level. Provide a highly detailed and technical explanation of any anomalies found.) " : "";
    const prompt = deepScanInstruction + `
Generate 5 realistic news headlines and short subtitles about AI, deepfakes, and cybersecurity.
Return ONLY a raw JSON array of objects without markdown formatting.
Each object must have:
- title (string, headline)
- subtitle (string, short summary)
`;
    const result = await model.generateContent(prompt);
    let rawText = result.response.text().replace(/```json/gi, "").replace(/```/g, "").trim();
    const news = JSON.parse(rawText);"""

new_news = """    const localRes = await axios.get(`${LOCAL_AI_URL}/news`);
    const news = localRes.data;"""

if old_news in code:
    code = code.replace(old_news, new_news)
    print("[OK] Replaced /news with Local AI.")
else:
    print("[WARN] Could not find exact old_news block.")

# 10. Replace /learning
old_learning = """    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash-lite" });
    const deepScanInstruction = userSettings.deepScan ? "(DEEP SCAN MODE ENABLED: Analyze at a rigorous forensic level. Provide a highly detailed and technical explanation of any anomalies found.) " : "";
    const prompt = deepScanInstruction + `
Generate 4 realistic learning hub articles about deepfake detection.
Return ONLY a raw JSON array of objects without markdown formatting.
Each object must have:
- title (string)
- content (string, a 3-paragraph article with tips on spotting AI)
- iconType (string, e.g. "school", "article", "shield")
`;
    const result = await model.generateContent(prompt);
    let rawText = result.response.text().replace(/```json/gi, "").replace(/```/g, "").trim();
    const articles = JSON.parse(rawText);"""

new_learning = """    const localRes = await axios.get(`${LOCAL_AI_URL}/learning`);
    const articles = localRes.data;"""

if old_learning in code:
    code = code.replace(old_learning, new_learning)
    print("[OK] Replaced /learning with Local AI.")
else:
    print("[WARN] Could not find exact old_learning block.")

with open("index.js", "w", encoding="utf-8") as f:
    f.write(code)

print("[INFO] Successfully updated index.js! New length:", len(code))
