import { useState } from 'react';
import { useNavigate } from 'react-router';
import { GradientButton } from '../components/GradientButton';
import { Scan, Shield, TrendingUp } from 'lucide-react';

export function OnboardingScreen() {
  const navigate = useNavigate();
  const [currentSlide, setCurrentSlide] = useState(0);

  const slides = [
    {
      icon: Scan,
      title: 'AI Media Detection',
      description: 'Upload any image or video to detect if it was generated by AI or is authentic.',
    },
    {
      icon: Shield,
      title: 'Advanced Analysis',
      description: 'Deep learning algorithms analyze compression, metadata, and visual artifacts.',
    },
    {
      icon: TrendingUp,
      title: 'Trust Score',
      description: 'Get instant authenticity scores and detailed reports for every media file.',
    },
  ];

  const handleNext = () => {
    if (currentSlide < slides.length - 1) {
      setCurrentSlide(currentSlide + 1);
    } else {
      navigate('/login');
    }
  };

  const CurrentIcon = slides[currentSlide].icon;

  return (
    <div className="h-screen w-full flex flex-col bg-gradient-to-br from-[#0a0118] via-[#1a0a30] to-[#0a0118] p-6">
      <div className="flex-1 flex flex-col items-center justify-center">
        <div className="relative mb-12">
          <div className="absolute inset-0 bg-gradient-to-r from-[var(--neon-purple)] to-[var(--neon-blue)] blur-3xl opacity-40" />
          <CurrentIcon size={100} className="text-[var(--neon-purple)] relative z-10" strokeWidth={1.5} />
        </div>

        <h2 className="text-3xl text-white mb-4 text-center">{slides[currentSlide].title}</h2>
        <p className="text-gray-400 text-center max-w-sm leading-relaxed">
          {slides[currentSlide].description}
        </p>

        <div className="flex gap-2 mt-12">
          {slides.map((_, index) => (
            <div
              key={index}
              className={`h-2 rounded-full transition-all duration-300 ${
                index === currentSlide
                  ? 'w-8 bg-gradient-to-r from-[var(--neon-purple)] to-[var(--neon-blue)]'
                  : 'w-2 bg-gray-600'
              }`}
            />
          ))}
        </div>
      </div>

      <div className="pb-8">
        <GradientButton onClick={handleNext} className="w-full">
          {currentSlide < slides.length - 1 ? 'Next' : 'Get Started'}
        </GradientButton>
      </div>
    </div>
  );
}
